name: Lint
on:
  push:
    branches:
    - master
jobs:
  main:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Yarn Install
      run: yarn
    - name: Create keys
      uses: finnp/create-file-action@1.0.0
      env:
        FILE_NAME = ${{ secrets.FILE_NAME }}
        FILE_DATA = ${{ secrets.FILE_DATA }}
    - name: Lint
      run: yarn lint
    - name: Build
      run: yarn build
    - name: Deploy
      run: yarn deploy
